import { buildActiveParryInterceptDiagnosis } from './active-parry-intercept-diagnosis.js';

// R18M.C5 — debug facade composition only.
// This module exposes injected actions/runtimes and read-only exchange getters; it owns no gameplay authority.

export function createShieldParryDebugApi({
  actions,
  runtimes,
  debugMode,
  getDebugStanceProfile,
  getExchangeState,
}) {
  return {
    startAttack: actions.startAttack,
    restartAttack: actions.restartAttack,
    setMode: actions.setMode,
    combat: runtimes.combat,
    attackRuntime: runtimes.attackRuntime,
    guardMachine: runtimes.guardMachine,
    predictivePresentation: runtimes.predictivePresentation,
    parryGate: runtimes.parryGate,
    freeCamera: runtimes.freeCamera,
    residualBodyReachRuntime: runtimes.residualBodyReachRuntime,
    residualStanceReachRuntime: runtimes.residualStanceReachRuntime,
    debugMode,
    get debugStanceProfile() { return Object.freeze({ ...getDebugStanceProfile() }); },
    refreshDebugStanceProfile: actions.refreshDebugStanceProfile,
    resetDebugStanceDefaults: actions.resetDebugStanceDefaults,
    swordGripConstraint: runtimes.swordGripConstraint,
    setEngagementSeparation: actions.setEngagementSeparation,
    resetLane: actions.resetLane,
    // R20E.1 WARNING: invasive mid-exchange. getWorldParrySurface advances anchor matrices
    // outside the frame pipeline and measurably flips outcomes (RIGHT@2.1m: passive polling
    // 3/3 blocked, polling this 3/3 body hits). Call it between exchanges only.
    captureBladeGeometry: actions.captureBladeGeometry,
    get laneGround() { return runtimes.laneController?.report ?? null; },
    get laneDefenderIntent() { return runtimes.laneController?.defenderIntent ?? 0; },
    get laneDefenderLateralIntent() { return runtimes.laneController?.defenderLateralIntent ?? 0; },
    get laneAttackerIntent() { return runtimes.laneController?.attackerIntent ?? 0; },
    get laneAttackerGait() { return runtimes.laneController?.attackerGait ?? null; },
    get laneDefenderGait() { return runtimes.laneController?.defenderGait ?? null; },
    get laneAttackerWalkSample() { return runtimes.laneController?.attackerWalkSample ?? null; },
    get engagementStance() { return runtimes.labScene?.engagementStance ?? null; },
    setDefenderYawOffset: (radians) => runtimes.labScene?.setDefenderYawOffset?.(radians) ?? null, // R19Q.1 facing seam (tests drive it directly)
    triggerParryNow: actions.triggerParryNow,
    dispatchParryInput: actions.dispatchParryInput,
    forceOldTwoActorB3: actions.forceOldTwoActorB3,
    get directOldB3Diagnostic() { return getExchangeState().directOldB3Diagnostic; },
    get latestPredictiveReport() { return getExchangeState().latestPredictiveReport; },
    get latestShieldLeadMotion() { return getExchangeState().latestShieldLeadMotion; },
    get latestLeadHandoff() { return getExchangeState().latestLeadHandoff; },
    get latestCombatResult() { return getExchangeState().latestCombatResult; },
    get latestParryInput() { return getExchangeState().latestParryInput; },
    get latestParryOpportunity() { return getExchangeState().latestParryOpportunity; },
    get latestContact() { return getExchangeState().latestContact; },
    get latestBodyHit() { return getExchangeState().latestBodyHit; },
    get latestParryConfirmation() { return getExchangeState().latestParryConfirmation; },
    get step3AContactTransfer() { return getExchangeState().step3AContactTransfer; },
    get latestGripConstraintReport() { return getExchangeState().latestGripConstraintReport; },
    get latestFinePlan() { return getExchangeState().latestFinePlan; },
    get latestFineTracking() { return getExchangeState().latestFineTracking; },
    get latestGuardCoverage() { return getExchangeState().latestGuardCoverage; },
    get latestSwingRelevance() { return getExchangeState().latestSwingRelevance; },
    get latestCloseRangePosture() { return getExchangeState().latestCloseRangePosture; },
    get latestConeGate() { return getExchangeState().latestConeGate; },
    get latestHiltClang() { return getExchangeState().latestHiltClang; },
    get latestGuardFacingPlan() { return getExchangeState().latestGuardFacingPlan; },
    get defenderFacingYawRadians() { return runtimes.laneController?.defenderFacingYawRadians ?? 0; },
    get latestGuardResidual() { return getExchangeState().latestGuardResidual; },
    get latestGuardStanceReach() { return getExchangeState().latestGuardStanceReach; },
    get latestParryWhiff() { return getExchangeState().latestParryWhiff; },
    get latestInterceptDriveReport() { return getExchangeState().latestInterceptDriveReport; },
    get latestVisualOwnershipBaseline() { return getExchangeState().latestVisualOwnershipBaseline; },
    get visualOwnershipTrace() { return getExchangeState().visualOwnershipTrace; },
    get latestInputSignal() { return getExchangeState().latestInputSignal; },
    get latestEngagementGround() { return getExchangeState().latestEngagementGround; },
    get latestRootDisplacement() { return getExchangeState().latestRootDisplacement; },
    get latestAttackerRootDisplacement() { return getExchangeState().latestAttackerRootDisplacement; },
    get latestDefenderRootDisplacement() { return getExchangeState().latestDefenderRootDisplacement; },
    get latestArmFling() { return getExchangeState().latestArmFling; },
    get latestArmFlingReport() { return getExchangeState().latestArmFlingReport; },
    get latestTorsoLean() { return getExchangeState().latestTorsoLean; },
    get latestTorsoLeanReport() { return getExchangeState().latestTorsoLeanReport; },
    get latestDefenderTorsoLeanReport() { return getExchangeState().latestDefenderTorsoLeanReport; },
    get blockReaction() { return getExchangeState().blockReaction; },
    get activeParryInterceptDiagnosis() {
      return buildActiveParryInterceptDiagnosis({
        attackSnapshot: runtimes.attackRuntime.snapshot,
        exchangeState: getExchangeState(),
      });
    },
  };
}
