import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('Action Studio uses the procedural KayKit character as its default character factory', async () => {
  const source = await readFile(new URL('../tools/action-studio/action-studio.js', import.meta.url), 'utf8');
  const external = await readFile(new URL('../tools/action-studio/studio-external-animation-controller.js', import.meta.url), 'utf8');
  assert.match(source, /createDefaultCharacter/);
  assert.doesNotMatch(source, /createBlockCharacter/);
  assert.match(external, /loadKayKitAnimationLibrary/);
  assert.match(external, /loadUal1AnimationLibrary/);
  assert.match(external, /loadUal2AnimationLibrary/);
  assert.match(external, /character\.registerAnimations/);
  assert.match(source, /ActionMotionPlayer/);
  assert.match(external, /createFittedAnimationBinding/);
  assert.match(source, /createStudioPreviewRuntime/);
  assert.match(source, /createWholeBodyMotionGuideOverlay/);
  assert.match(source, /createStudioMotionGuideEditor/);
  assert.match(source, /bakeStudioMotionConstraints/);
  assert.match(source, /createStudioPoseDragController/);
  assert.match(source, /createStudioBlockingWorkflow/);
  assert.match(source, /createStudioProjectIoController/);
  assert.match(source, /character\.update\(deltaSeconds, preview\.camera\)/);
  assert.ok(source.split(/\r?\n/).length < 700, 'Action Studio entry should stay a thin composition root');
  assert.doesNotMatch(source, /setCharacterRenderStyle|data-character-style/);
  assert.match(source, /sword\.update\(\)/);
  assert.match(source, /sword\.setNodesVisible/);
  assert.match(source, /sword\.setGlowVisible/);
  assert.match(source, /sword\.getSweepSegment/);
});

test('Action Studio separates preview, project, and editor view responsibilities', async () => {
  const preview = await readFile(new URL('../tools/action-studio/studio-preview-runtime.js', import.meta.url), 'utf8');
  const project = await readFile(new URL('../tools/action-studio/studio-project.js', import.meta.url), 'utf8');
  const editorView = await readFile(new URL('../tools/action-studio/studio-editor-view.js', import.meta.url), 'utf8');
  const motionEditor = await readFile(new URL('../tools/action-studio/studio-motion-guide-editor.js', import.meta.url), 'utf8');
  const motionOverlay = await readFile(new URL('../tools/action-studio/studio-motion-guide-overlay.js', import.meta.url), 'utf8');
  const constraintBaker = await readFile(new URL('../tools/action-studio/studio-motion-constraint-baker.js', import.meta.url), 'utf8');
  const poseDrag = await readFile(new URL('../tools/action-studio/studio-pose-drag-controller.js', import.meta.url), 'utf8');
  const axisGizmo = await readFile(new URL('../tools/action-studio/studio-axis-gizmo.js', import.meta.url), 'utf8');
  const dragSolver = await readFile(new URL('../src/animation/whole-body-drag-solver.js', import.meta.url), 'utf8');
  const blocking = await readFile(new URL('../tools/action-studio/studio-blocking-workflow.js', import.meta.url), 'utf8');
  const projectIo = await readFile(new URL('../tools/action-studio/studio-project-io-controller.js', import.meta.url), 'utf8');
  const external = await readFile(new URL('../tools/action-studio/studio-external-animation-controller.js', import.meta.url), 'utf8');
  assert.match(preview, /createStudioPreviewRuntime/);
  assert.match(preview, /sword\.trailTip\.getWorldPosition/);
  assert.match(project, /createStudioProject/);
  assert.match(editorView, /renderTimelineView/);
  assert.match(motionEditor, /createStudioMotionGuideEditor/);
  assert.match(motionEditor, /Bake Pose Keys/);
  assert.match(motionOverlay, /WHOLE_BODY_MOTION_GUIDES/);
  assert.match(motionOverlay, /Raycaster/);
  assert.match(motionOverlay, /stage-drag/);
  assert.match(motionOverlay, /GUIDE_WINDUP_TARGET/);
  assert.match(motionOverlay, /windupPullback/);
  assert.match(motionEditor, /Windup body load/);
  assert.match(constraintBaker, /WINDUP_HAND_POSE_KEYS/);
  assert.match(constraintBaker, /handslot\.r/);
  assert.match(constraintBaker, /SECONDARY_GRIP_POSE_KEYS/);
  assert.match(constraintBaker, /sword\.secondaryGrip/);
  assert.match(poseDrag, /DIRECT_POSE_MANIPULATORS/);
  assert.match(poseDrag, /posePinLeftFoot/);
  assert.match(poseDrag, /solveWholeBodyDragPose/);
  assert.match(poseDrag, /RIGHT HAND · WEAPON.*0xff3b81.*0\.082/);
  assert.match(poseDrag, /pointerup/);
  assert.match(poseDrag, /axisConstrainedTarget/);
  assert.match(poseDrag, /poseAxisSpace/);
  assert.match(poseDrag, /event\.shiftKey/);
  assert.match(axisGizmo, /POSE_AXIS_GIZMO/);
  assert.match(axisGizmo, /DIRECT_POSE_AXES/);
  assert.match(axisGizmo, /snapAxisDragDistance/);
  assert.match(dragSolver, /activatedWholeBody/);
  assert.match(dragSolver, /WHOLE_BODY_JOINT_EFFECTORS/);
  assert.match(dragSolver, /secondaryErrors/);
  assert.match(dragSolver, /maxStretch/);
  assert.match(blocking, /captureNextBlockingKey/);
  assert.match(blocking, /BLOCKING_\$\{kind\.toUpperCase\(\)\}_GHOST/);
  assert.match(blocking, /BLOCKING_TRAJECTORY/);
  assert.match(blocking, /sword\.trailTip\.getWorldPosition/);
  assert.match(projectIo, /downloadProject/);
  assert.match(projectIo, /ACTION_STUDIO_AUTOSAVE_V1/);
  assert.match(external, /loadUal1AnimationLibrary/);
  assert.match(external, /loadUal2AnimationLibrary/);
  assert.match(external, /RETARGET PREVIEW/);
  assert.match(external, /readAnimationBindingView\(source\)/);
});

test('Action Studio exposes explicit KayKit runtime controls and GLTFLoader', async () => {
  const template = await readFile(new URL('../tools/action-studio/index.template.html', import.meta.url), 'utf8');
  assert.match(template, /GLTFLoader\.js/);
  assert.match(template, /id="animationPackSource"/);
  assert.match(template, /UAL1 Sword Basics/);
  assert.match(template, /UAL2 Sword Combat/);
  assert.match(template, /id="loadKayKitAnimations"/);
  assert.match(template, /id="kaykitClip"/);
  assert.match(template, /id="playKayKitAnimation"/);
  assert.match(template, /id="bindKayKitAnimation"/);
  assert.match(template, /id="fitKayKitAnimation"/);
  assert.match(template, /id="clearAnimationBinding"/);
  assert.match(template, /id="wholeBodyMotionEditor"/);
  assert.match(template, /semantic guides → Pose Keys/);
  assert.match(template, /點選手腳／肘膝節點顯示 XYZ 軸/);
  assert.match(template, /id="poseDragEnabled"/);
  assert.match(template, /id="posePinLeftFoot"/);
  assert.match(template, /id="posePinRightFoot"/);
  assert.match(template, /id="poseDragCoupling"/);
  assert.match(template, /id="poseJointHandles"/);
  assert.match(template, /id="poseDragPlane"/);
  assert.match(template, /Direct Pose V3/);
  assert.match(template, /id="poseAxisGizmo"/);
  assert.match(template, /id="poseAxisSpace"/);
  assert.match(template, /id="poseAxisReadout"/);
  assert.match(template, /1\.05×/);
  assert.match(template, /id="captureNextKey"/);
  assert.match(template, /id="blockingFrameStep"/);
  assert.match(template, /id="blockingGhostPrevious"/);
  assert.match(template, /id="blockingGhostNext"/);
  assert.match(template, /id="blockingTrajectories"/);
  assert.match(template, /id="downloadProject"/);
  assert.match(template, /id="openProjectFile"/);
  assert.match(template, /id="restoreAutosave"/);
  assert.match(template, /id="projectFileInput"/);
  assert.match(template, /23 generated bones/);
  assert.match(template, /id="toggleRigNodes"/);
  assert.match(template, /id="toggleRigGlow"/);
  assert.doesNotMatch(template, />Hybrid<|data-character-style/);
  assert.match(template, /id="weaponRigStatus"/);
  assert.match(template, /11 weapon bones/);
  assert.match(template, /exact v3 edges/);
});

test('default character dependency graph does not import a source KayKit model', async () => {
  const factory = await readFile(new URL('../src/character/default-character.js', import.meta.url), 'utf8');
  const character = await readFile(new URL('../src/character/procedural-kaykit-character.js', import.meta.url), 'utf8');
  const rig = await readFile(new URL('../src/character/procedural-kaykit-rig.js', import.meta.url), 'utf8');
  assert.doesNotMatch(`${factory}\n${character}\n${rig}`, /GLTFLoader|knight\.glb|EMBED\.knight/);
  assert.match(character, /createProceduralKayKitRig/);
  assert.match(character, /sampleAnimation/);
  assert.match(rig, /new THREE\.Bone/);
  assert.match(rig, /createKayKitV3LineAppearance/);
  assert.doesNotMatch(rig, /buildProceduralMeshes|BoxGeometry|MeshStandardMaterial/);
});
