import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { startStaticServer } from '../tools/static-server.mjs';

const ROOT = new URL('../', import.meta.url);
const read = (relative) => readFileSync(new URL(relative, ROOT), 'utf8');

// R20Z.1 - the wiring that makes the browser gates real.
//
// These assert on configuration and generated output, which is not the same thing as asserting on
// implementation text: the config IS the subject. A test that says "ci.yml runs the gate" is the
// only way to notice the gate being dropped, and dropping it is silent by nature.

test('R20Z.1 the probe page is the lab page, minus the CDN it cannot reach', () => {
  execFileSync(process.execPath, ['build/build-probe-lab.mjs'], { cwd: fileURLToPath(ROOT) });
  const lab = read('tools/action-studio/shield-driven-contact-coupling-lab.html');
  const probe = read('tools/action-studio/probe.lab.html');

  // The generated page carries a banner, then the lab verbatim with two tags swapped. Undo the two
  // swaps and it must be the lab again, character for character - that equality is what stops the
  // drift the hand-synced copy accumulated over several stages.
  const restored = probe
    .slice(probe.indexOf('<!doctype html>'))
    .replace('<script src="/node_modules/three/build/three.min.js"></script>',
      '<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>')
    .replace('<script src="/node_modules/three/examples/js/loaders/GLTFLoader.js"></script>',
      '<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/loaders/GLTFLoader.js"></script>');
  assert.equal(restored, lab, 'the probe page must differ from the lab only by its script sources');

  assert.match(probe, /Generated by build\/build-probe-lab\.mjs/, 'and must say it is generated');
  assert.ok(!probe.includes('https://cdn'), 'a page with no egress cannot keep a CDN reference');
});

test('R20Z.1 the local Three.js is the same Three.js the published page loads', () => {
  // The probe page swaps a CDN copy for node_modules. If those two ever differ, every browser gate
  // is measuring a different renderer than the one players get, and nothing else would say so.
  const lab = read('tools/action-studio/shield-driven-contact-coupling-lab.html');
  const cdnVersion = lab.match(/three@([0-9.]+)\/examples/)?.[1];
  const cdnRelease = lab.match(/three\.js\/r([0-9]+)\/three\.min\.js/)?.[1];
  const declared = JSON.parse(read('package.json')).devDependencies?.three;
  assert.ok(cdnVersion, 'the lab must name the Three.js version it loads');
  assert.equal(declared, cdnVersion, `package.json declares three@${declared}, the page loads ${cdnVersion}`);
  // r128 and 0.128.0 are the same release named two ways; keep them agreeing.
  assert.equal(cdnRelease, cdnVersion.split('.')[1]);
});

test('R20Z.1 the gates are wired into CI, and CI can reach a browser', () => {
  const ci = read('.github/workflows/ci.yml');
  assert.match(ci, /npm run verify:combat/, 'the browser gates must run in CI');
  assert.match(ci, /CHROME_PATH:/, 'and CI must say where the browser is');
  const scripts = JSON.parse(read('package.json')).scripts;
  assert.equal(scripts['verify:combat'], 'node build/verify-combat.mjs');
  assert.equal(scripts['build:probe-lab'], 'node build/build-probe-lab.mjs');

  const runner = read('build/verify-combat.mjs');
  // Both gates, or the command is only pretending to be one.
  assert.match(runner, /verify-golden-grid\.mjs/);
  assert.match(runner, /verify-shield-parry-gate\.mjs/);
  assert.match(runner, /build-probe-lab\.mjs/, 'the page must be regenerated before it is driven');
});

test('R20Z.1 the static server serves the repository and refuses to leave it', async () => {
  const served = await startStaticServer({ root: fileURLToPath(ROOT), port: 0 });
  try {
    const page = await fetch(`${served.url}/tools/action-studio/probe.lab.html`);
    assert.equal(page.status, 200);
    assert.match(page.headers.get('content-type'), /text\/html/);

    const module = await fetch(`${served.url}/src/combat/lane-walk-cycle.js`);
    assert.equal(module.status, 200);
    // ES modules will not load as octet-stream, which is the whole reason the gates need a server.
    assert.match(module.headers.get('content-type'), /javascript/);

    const missing = await fetch(`${served.url}/nothing-here.js`);
    assert.equal(missing.status, 404);

    const escape = await fetch(`${served.url}/../../etc/passwd`);
    assert.ok(escape.status === 403 || escape.status === 404, `traversal returned ${escape.status}`);
  } finally {
    await served.close();
  }
});
