export const SHIELD_PARRY_EXCHANGE_STATE_KEYS = Object.freeze([
  'previousShieldLeadSurface',
  'firstContact',
  'latestContact',
  'latestBodyHit',
  'latestCombatResult',
  'latestCombatUpdate',
  'latestFinePlan',
  'latestGuardCoverage',
  'latestSwingRelevance',
  'latestGuardResidual',
  'latestGuardStanceReach',
  'latestFineTracking',
  'latestPredictiveAnalysis',
  'latestReachableInterceptTarget',
  'latestInterceptDriveReport',
  'interceptDriveTrace',
  'latestVisualOwnershipBaseline',
  'visualOwnershipTrace',
  'latestPredictiveReport',
  'latestPredictiveHandoff',
  'latestShieldLeadMotion',
  'latestLeadHandoff',
  'directOldB3Diagnostic',
  'latestParryInput',
  'latestParryOpportunity',
  'latestParryConfirmation',
  'frozenAttackerContactPose',
  'canonicalAttackerOldB3Pose',
  'canonicalAttackerOldB3WorldSilhouette',
  'step3AContactTransfer',
  'latestGripConstraintReport',
  'latestLiveSurfaceAtContact',
  'step3AReleaseBlend',
  'visibleOldB3Peak',
  'latchedDefenderDeflectReleaseGate',
  'latestEngagementGround',
  'latestRootDisplacement',
  'latestAttackerRootDisplacement',
  'latestDefenderRootDisplacement',
  'latestArmFling',
  'latestArmFlingReport',
  'latestTorsoLean',
  'latestTorsoLeanReport',
  'latestDefenderTorsoLeanReport',
  'blockReaction',
  'latestParryWhiff',
  'whiffProbeFrames',
  'closestWhiffApproach',
  'outsideActiveContact',
  'latestInputSignal',
  'parryPromptHold',
  'parryPromptHoldSequence',
]);

function createResetSnapshot() {
  return {
    previousShieldLeadSurface: null,
    firstContact: null,
    latestContact: null,
    latestBodyHit: null,
    latestCombatResult: null,
    latestCombatUpdate: null,
    latestFinePlan: null,
    latestGuardCoverage: null,
    latestSwingRelevance: null,
    latestGuardResidual: null,
    latestGuardStanceReach: null,
    latestFineTracking: null,
    latestPredictiveAnalysis: null,
    latestReachableInterceptTarget: null,
    latestInterceptDriveReport: null,
    interceptDriveTrace: [],
    latestVisualOwnershipBaseline: null,
    visualOwnershipTrace: [],
    latestPredictiveReport: null,
    latestPredictiveHandoff: null,
    latestShieldLeadMotion: null,
    latestLeadHandoff: null,
    directOldB3Diagnostic: null,
    latestParryInput: null,
    latestParryOpportunity: null,
    latestParryConfirmation: null,
    frozenAttackerContactPose: null,
    canonicalAttackerOldB3Pose: null,
    canonicalAttackerOldB3WorldSilhouette: null,
    step3AContactTransfer: null,
    latestGripConstraintReport: null,
    latestLiveSurfaceAtContact: null,
    step3AReleaseBlend: null,
    visibleOldB3Peak: null,
    latchedDefenderDeflectReleaseGate: null,
    latestEngagementGround: null,
    latestRootDisplacement: null,
    latestAttackerRootDisplacement: null,
    latestDefenderRootDisplacement: null,
    latestArmFling: null,
    latestArmFlingReport: null,
    latestTorsoLean: null,
    latestTorsoLeanReport: null,
    latestDefenderTorsoLeanReport: null,
    blockReaction: null,
    latestParryWhiff: null,
    whiffProbeFrames: 0,
    closestWhiffApproach: null,
    outsideActiveContact: null,
    latestInputSignal: null,
    parryPromptHold: null,
    parryPromptHoldSequence: null,
  };
}

export function createShieldParryExchangeState() {
  return createResetSnapshot();
}

export function resetShieldParryExchangeState(state, {
  previousShieldLeadSurface = null,
} = {}) {
  if (!state || typeof state !== 'object') {
    throw new TypeError('resetShieldParryExchangeState requires a mutable state object');
  }
  Object.assign(state, createResetSnapshot());
  state.previousShieldLeadSurface = previousShieldLeadSurface;
  return state;
}
