// Close the loop: predict the -0.604 residual from the basis cross-terms alone.
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as ThreeModule from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { createDefaultCharacter } from '../src/character/default-character.js';
import { retargetConvertedSkyrimGltf } from '../src/animation/skyrim-converted-animation-library.js';
import { SKYRIM_BONE_RETARGETS, resolveSkyrimSourceNodes } from '../src/animation/skyrim-animation-retarget.js';
import { parseSourceGlb } from '../build/skyrim-grip-reach.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const THREE={...ThreeModule,GLTFLoader}; const V=()=>new THREE.Vector3();
const rel='assets/skyrim/guard/converted/shd_blockbashpower.source.glb';
const SEL=SKYRIM_BONE_RETARGETS.filter(r=>['root','pelvis','head'].includes(r.id));
const gltf=await parseSourceGlb(THREE,await readFile(path.join(ROOT,rel)));
const character=createDefaultCharacter(THREE);
const clip=retargetConvertedSkyrimGltf(THREE,gltf,character.rig,{id:'p',file:'x',clipId:'S/p',role:'m'},{fps:30});
character.registerAnimations([clip]);
const sroot=gltf.scene,R=resolveSkyrimSourceNodes(sroot,SEL),bones=character.rig.bones;
const sPos=()=>{sroot.updateMatrixWorld(true);return{root:R.nodes.root.getWorldPosition(V()),pelvis:R.nodes.pelvis.getWorldPosition(V()),head:R.nodes.head.getWorldPosition(V())};};
const tPos=()=>{character.object3d.updateMatrixWorld(true);return{root:bones.root.getWorldPosition(V()),pelvis:bones.hips.getWorldPosition(V()),head:bones.head.getWorldPosition(V())};};
const sp0=sPos(),tp0=tPos();
const sStat=Math.abs(sp0.head.z-sp0.root.z), tStat=tp0.head.y-tp0.root.y;
const sRestVec=sp0.pelvis.clone().sub(sp0.root);
const bq=new THREE.Quaternion().fromArray(clip.userData.basisCalibration.quaternion);
const M=new THREE.Matrix4().makeRotationFromQuaternion(bq).elements;
const scale=clip.userData.translationScale;
const sStat3D=sp0.head.distanceTo(sp0.root);
const dur=character.getAnimationDuration(clip.name),sdur=gltf.animations[0].duration;
const m=new THREE.AnimationMixer(sroot);const a=m.clipAction(gltf.animations[0]);
a.setLoop(THREE.LoopOnce,1);a.clampWhenFinished=true;a.play();
const f=0.715;
m.setTime(sdur*f);const sp=sPos();character.sampleAnimation(clip.name,dur*f);const tp=tPos();
const sD=sp.pelvis.clone().sub(sp.root).sub(sRestVec);
const srcVert=sD.z/sStat;
const tgtVert=(tp.pelvis.y-tp.root.y-(tp0.pelvis.y-tp0.root.y))/tStat;
const k=scale/tStat;
const predicted=k*(M[1]*sD.x+M[5]*sD.y+M[9]*sD.z);
console.log(`f=${f}  source pelvis world delta (Z-up source): x ${sD.x.toFixed(4)}  y(fwd) ${sD.y.toFixed(4)}  z(up) ${sD.z.toFixed(4)}`);
console.log(`  source vertical delta  ${(srcVert*100).toFixed(4)} pts   (= sD.z / ${sStat.toFixed(4)})`);
console.log(`  target vertical delta  ${(tgtVert*100).toFixed(4)} pts   closed-form ${(predicted*100).toFixed(4)} pts`);
console.log(`  probe residual         ${((tgtVert-srcVert)*100).toFixed(4)} pts`);
console.log('  decomposed:');
console.log(`    forward-leak  M[y][srcY]*sD.y*k = ${(k*M[5]*sD.y*100).toFixed(4)} pts   (basis row picks up ${M[5].toFixed(6)} of the source's FORWARD axis)`);
console.log(`    z-gain+denom  (${M[9].toFixed(6)}*k - 1/${sStat.toFixed(4)})*sD.z = ${((k*M[9]-1/sStat)*sD.z*100).toFixed(4)} pts`);
console.log(`    x-leak        ${(k*M[1]*sD.x*100).toFixed(6)} pts`);
console.log(`  sum = ${(((k*M[5]*sD.y)+((k*M[9]-1/sStat)*sD.z)+(k*M[1]*sD.x))*100).toFixed(4)} pts`);
console.log(`\n  scale/tStat = ${k.toExponential(8)}   1/|head-root|3D = ${(1/sStat3D).toExponential(8)}   1/|head-root|.z = ${(1/sStat).toExponential(8)}`);
